### ISSUE TITLE
Modular

### ISSUE THREAD

**Issue by seven332** [seven332/Image#10]
Decoders consume too much disk space. Additional, Not every application needs all these decoders. There must be a way to select only the decoders in need.

This library should be separated into several libraries. One main library, the entry point. Several image-decoder libraries. Only the decoders in need are added as dependencies. 

Decoders must be registered before the main .so file loaded. In the `JNI_OnLoad()` of the main .so file, use `dlopen()` to load the .so files for decoders, use `dlsym()` to create decoder instances.

**Comment by seven332** [comment]
More Gradle module must be created to achieve it. One for a library with all decoders. One for a library without docoders. And each decoder needs a module.

**Comment by msm595** [comment]
Currently working on this here: https://github.com/msm595/Image/tree/separate-modules-post-rebase. Some more cleanup needed, but the basic blocks (separate .so vs a single .so) are there.

**Comment by seven332** [comment]
That's cool. The directory structure is better.
