### ISSUE TITLE
Support interlaced PNG

### ISSUE THREAD

**Issue by inorichi** [seven332/Image#2]
First of all, thank you for this great library. I recently started using it as an additional image decoder in my project and I received today [this issue](https://github.com/inorichi/tachiyomi/issues/514).

I've been testing it and it seems `BitmapDecoder` doesn't support interlaced PNG (see screenshot in the linked issue). I've been reading through `image_png.c` but I can't find anything relevant.

**Comment by seven332** [comment]
Yes, it is a bug. I'm trying to fix it.

**Comment by seven332** [comment]
I need to rewrite the image-scale part to fix the bug. It will take some time.

**Comment by seven332** [comment]
This bug should be fixed now.

**Comment by inorichi** [comment]
Can confirm it works. Thanks!
