### ISSUE TITLE
Colors different compared to source image

### ISSUE THREAD

**Issue by nshishov** [seven332/Image#6]
Hi!

There is Tachiyomi application that uses this library for image decoding and I spotted a problem
inorichi/tachiyomi#589

When application uses this library for image decoding color tones go off for JPG images.

Can you please help?

**Comment by seven332** [comment]
Could you please give me the jpg file?

I use the library libjpeg-turbo to decode jpg image. But it doesn't support convert cmyk to rgb565 directly. I add the feature by my own, and it's not well tested.

**Comment by seven332** [comment]
libjpeg-turbo enable rgb565 dithering in default, but it makes color different.
I disable it now. The color should be right.

**Comment by nshishov** [comment]
Thanks!

**Comment by nshishov** [comment]
I have just checked new build of Tachiyomi with this fix and it looks much better now.
Thanks again.
